user_controllers:
    resource:
        path: ../src/User/Controller/
        namespace: App\User\Controller
    type: attribute

listing_controllers:
    resource:
        path: ../src/Listing/Controller/
        namespace: App\Listing\Controller
    type: attribute

review_controllers:
    resource:
        path: ../src/Review/Controller/
        namespace: App\Review\Controller
    type: attribute

messaging_controllers:
    resource:
        path: ../src/Messaging/Controller/
        namespace: App\Messaging\Controller
    type: attribute

shared_controllers:
    resource:
        path: ../src/Shared/Controller/
        namespace: App\Shared\Controller
    type: attribute
