# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Storage Services
    App\Storage\LocalStorageService:
        arguments:
            $uploadBasePath: '%kernel.project_dir%/public/uploads'
            $publicBaseUrl: '/uploads'

    App\Storage\R2StorageService:
        arguments:
            $endpoint: '%env(R2_ENDPOINT)%'
            $region: '%env(R2_REGION)%'
            $bucket: '%env(R2_BUCKET)%'
            $accessKeyId: '%env(R2_ACCESS_KEY_ID)%'
            $secretAccessKey: '%env(R2_SECRET_ACCESS_KEY)%'
            $publicBaseUrl: '%env(R2_PUBLIC_BASE_URL)%'

    # Storage Interface - change alias to switch storage
    # Options: App\Storage\LocalStorageService or App\Storage\R2StorageService
    App\Storage\StorageInterface:
        alias: App\Storage\R2StorageService

    # Listing Image Service with storage driver parameter
    App\Service\ListingImageService:
        arguments:
            $storageDriver: 'local'  # Change to 'r2' when using R2
