app.swagger_ui:
    path: /auth/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger_json:
    path: /auth/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

