nelmio_cors:
    defaults:
        allow_origin: ['*']
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Content-Type', 'Authorization']
        allow_credentials: false
        max_age: 3600
    paths:
        '^/':
            allow_origin: ['*']
